services:
  frontend:
    image: node:24-alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:5042
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    image: node:24-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5042:5042"
    command: sh -c "apk add --no-cache chromium nss freetype harfbuzz ca-certificates ttf-freefont && npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=5042
      - MONGODB_URI=mongodb://database:27017/pere-sapin
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - FRONTEND_URL=http://frontend:3000
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    networks:
      - app-network
    depends_on:
      - database
  database:
    image: mongo:latest
    container_name: database
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data:
    driver: local
