replicaCount: 1
image:
  repository: ghcr.io/H1B0B0/pere-sapin-frontend
  tag: "latest"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-secret
service:
  type: ClusterIP
  port: 3000
env:
  NODE_ENV: production
  NEXT_PUBLIC_API_URL: http://backend.default.svc.cluster.local.:5042
resources: {}

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: les-chalets-du-pere-sapin.seafarer-cloud.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: les-chalets-du-pere-sapin-tls
      hosts:
        - les-chalets-du-pere-sapin.seafarer-cloud.io

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podLabels: {}

podSecurityContext: {}

securityContext: {}

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

livenessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

volumeMounts: []

volumes: []
