replicaCount: 1
image:
  repository: ghcr.io/H1B0B0/pere-sapin-backend
  tag: "latest"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-secret
service:
  type: ClusterIP
  port: 5042
env:
  NODE_ENV: production
  PORT: 5042
  MONGODB_URI: mongodb://database:27017/pere-sapin
  JWT_SECRET: your-super-secret-jwt-key-change-in-production
  FRONTEND_URL: http://frontend:3000
  PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
resources: {}
