replicaCount: 1
image:
  repository: ghcr.io/H1B0B0/pere-sapin-backend
  tag: "latest"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-secret
service:
  type: ClusterIP
  port: 5042
env:
  NODE_ENV: production
  PORT: 5042
  MONGODB_URI: mongodb+srv://pere_sapin:0VpQ0ZYRLZIukxHB@pere-sapin.x3xce8o.mongodb.net/?retryWrites=true&w=majority&appName=Pere-sapin
  FRONTEND_URL: http://frontend.default.svc.cluster.local.:3000
  PUBLIC_FRONTEND_URL: https://les-chalets-du-pere-sapin.seafarer-cloud.io
  PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

secrets:
  jwtSecret: "change-this-super-secret-jwt-key-in-production-minimum-32-chars"

resources: {}

# Ingress configuration (disabled for backend - only frontend should be exposed)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

# Standard Helm chart values
autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podLabels: {}

podSecurityContext: {}

securityContext: {}

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

livenessProbe:
  httpGet:
    path: /
    port: 5042
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: 5042
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

volumeMounts: []

volumes: []
