name: Deploy with Helm

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"

      - name: Set up Kubeconfig
        run: |
          echo "$KUBECONFIG_DATA" > kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

      - name: Prepare lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Derive image tag from triggering run
        run: |
          REF="${{ github.event.workflow_run.ref }}"
          if echo "$REF" | grep -q '^refs/tags/'; then
            TAG="${REF#refs/tags/}"
          else
            TAG="${REF#refs/heads/}"
          fi
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Deploy backend with Helm
        run: |
          helm upgrade --install backend ./helm-charts/backend \
            --set image.repository=ghcr.io/${{ env.OWNER_LC }}/pere-sapin-backend \
            --set image.tag=v${{ env.IMAGE_TAG }} \
            --set secrets.jwtSecret="${{ secrets.JWT_SECRET }}" \
            --kubeconfig kubeconfig

      - name: Deploy frontend with Helm
        run: |
          helm upgrade --install frontend ./helm-charts/frontend \
            --set image.repository=ghcr.io/${{ env.OWNER_LC }}/pere-sapin-frontend \
            --set image.tag=v${{ env.IMAGE_TAG }} \
            --kubeconfig kubeconfig
