name: Deploy Frontend Only

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.REGISTRY_PAT }}

      - name: Derive SHORT_TAG (drop leading v only)
        run: |
          TAG="${{ inputs.tag }}"
          if [[ "$TAG" == v* ]]; then
            echo "SHORT_TAG=${TAG#v}" >> $GITHUB_ENV
          else
            echo "SHORT_TAG=$TAG" >> $GITHUB_ENV
          fi

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/pere-sapin-frontend:${{ inputs.tag }}
            ghcr.io/${{ env.OWNER_LC }}/pere-sapin-frontend:latest
            ghcr.io/${{ env.OWNER_LC }}/pere-sapin-frontend:${{ env.SHORT_TAG }}
          build-args: |
            NODE_ENV=production

  deploy-frontend:
    needs: build-and-push-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"

      - name: Set up Kubeconfig
        run: |
          echo "$KUBECONFIG_DATA" > kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

      - name: Prepare lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Deploy frontend with Helm
        run: |
          helm upgrade --install frontend ./helm-charts/frontend \
            --set image.repository=ghcr.io/${{ env.OWNER_LC }}/pere-sapin-frontend \
            --set image.tag=${{ inputs.tag }} \
            --kubeconfig kubeconfig