name: Deploy with Helm

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"

      - name: Set up Kubeconfig
        run: |
          echo "$KUBECONFIG_DATA" | base64 -d > kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

      - name: Deploy backend with Helm
        run: |
          helm upgrade --install backend ./helm-charts/backend \
            --set image.repository=ghcr.io/${{ github.repository_owner }}/pere-sapin-backend \
            --set image.tag=${{ github.event.workflow_run.head_branch }} \
            --kubeconfig kubeconfig

      - name: Deploy frontend with Helm
        run: |
          helm upgrade --install frontend ./helm-charts/frontend \
            --set image.repository=ghcr.io/${{ github.repository_owner }}/pere-sapin-frontend \
            --set image.tag=${{ github.event.workflow_run.head_branch }} \
            --kubeconfig kubeconfig
